; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:sensor]
platform = atmelavr
board = nanoatmega328
framework = arduino
lib_deps = 
	matthew-dickson-epic/TimeInterrupt@^1.0.2
	SPI
	Wire
	u8g2

upload_port = /dev/tty.usbserial-140
lib_extra_dirs = common

; [env:pannel_avr]
; platform = atmelavr
; board = nanoatmega328
; framework = arduino
; upload_port = /dev/tty.usbserial-142
; build_src_filter = +<main-pannel.cpp> +<include/*.h> +<lib/>
; lib_deps = 
; 	Wire
; 	u8g2
; 	matthew-dickson-epic/TimeInterrupt@^1.0.2

; [env:pannel_esp]
; platform = ststm32
; board = bluepill_f103c8
; debug_tool = jlink
; upload_protocol = jlink
; build_flags =
;     -DBOARD_BLUEPILL
; build_src_filter = +<main-pannel.cpp> +<include/*.h> +<lib/>
; lib_deps = 
; 	arduino
; 	Wire
; 	u8g2
; 	khoih-prog/TimerInterrupt_Generic@^1.13.0