; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:avr-pannel]
platform = atmelavr
board = nanoatmega328
framework = arduino
lib_deps = 
	SPI
	Wire
	u8g2
	matthew-dickson-epic/TimeInterrupt@^1.0.2
upload_port = /dev/tty.usbserial-1340
upload_speed = 115200
build_src_filter = +<*.cpp> +<include/*.h> +<lib/**/*.h> +<lib/**/*.cpp> -<main-sensor.cpp>
build_flags = 
	-D PANNEL_NANO
	-D BUTTONS_POLLING
	-D SERIAL_BUFFER_SIZE=256

[env:stm-panel]
platform = ststm32
framework = arduino
board = bluepill_f103c8
; upload_port = /dev/tty.usbmodem13401
; upload_protocol = dfu
; upload_flags = -c set CPUTAPID 0x2ba01477
upload_protocol = jlink
upload_port = jlink
build_src_filter = +<*.cpp> +<include/*.h> +<lib/**/*.h> +<lib/**/*.cpp> +<**/ui.cpp> -<main-sensor.cpp>
lib_deps = 
	u8g2
	TimerInterrupt_Generic@^1.13.0
build_flags = 
	-D PANNEL_STM32

[env:sensor]
platform = atmelavr
board = nanoatmega328
framework = arduino
lib_deps = 
	matthew-dickson-epic/TimeInterrupt@^1.0.2
upload_port = /dev/tty.usbserial-1340
build_src_filter = +<*.cpp> +<include/*.h> +<lib/**/*.h> +<lib/**/*.cpp> -<**/ui.h> -<**/ui.cpp> -<main-pannel.cpp>
build_flags = 
	-D SENSOR

